# Random Forest

In [1]:
#Importing libraries
import numpy as np
import pandas as pd

In [2]:
#Reading a csv file
df = pd.read_csv('titanic_cleaned.csv')

In [3]:
#Dimension of a dataframe
df.shape

(891, 25)

In [4]:
#First 5 rows of a dataframe
df.head()

Survived   Age     Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  \
0         0  22.0   7.2500         0         0         1           0   
1         1  38.0  71.2833         1         0         0           1   
2         1  26.0   7.9250         0         0         1           1   
3         1  35.0  53.1000         1         0         0           1   
4         0  35.0   8.0500         0         0         1           0   

   Sex_male  SibSp_0  SibSp_1  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0         1        0        1  ...        1        0        0        0   
1         0        0        1  ...        1        0        0        0   
2         0        1        0  ...        1        0        0        0   
3         0        0        1  ...        1        0        0        0   
4         1        1        0  ...        1        0        0        0   

   Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0        0        0        0           0           0           1  
1        0        0        0           1           0           0  
2        0        0        0           0           0           1  
3        0        0        0           0           0           1  
4        0        0        0           0           0           1  

[5 rows x 25 columns]

In [5]:
#Seperate Independent and Dependent variable
X = df.drop('Survived', axis=1)
y = df['Survived']

In [6]:
#Creating Train and Test dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=11)

### Implement Decision Tree

In [7]:
#Importing Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier

In [8]:
#Creating an instance of DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=11)

In [9]:
#Training a model
dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [10]:
#Make a prediction on train dataset
y_pred = dt.predict(X_test)
y_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0], dtype=int64)

In [11]:
#Calculating score on Training data
dt.score(X_train, y_train)

0.9831460674157303

In [12]:
#Calculating score on Test data
dt.score(X_test, y_test)

0.7430167597765364

### Implement Random Forest Model

In [13]:
#Import Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

In [14]:
#Create an instance of RandomForestClassifier
rf = RandomForestClassifier(random_state=11)

In [15]:
#Training a model
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=11)

In [16]:
#Make a prediction on Test data
y_pred = rf.predict(X_test)
y_pred

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0], dtype=int64)

In [17]:
#Calculating score on Train data
rf.score(X_train, y_train)

0.9831460674157303

In [18]:
#Calculating score on Test data
rf.score(X_test, y_test)

0.8156424581005587

In [19]:
#Creating Random Forest model with some Hyperparameters
rf = RandomForestClassifier(n_estimators=100, max_depth=12)

In [20]:
#Training a model
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=12)

In [21]:
#Make a prediction on Test data
y_pred = rf.predict(X_test)
y_pred

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0], dtype=int64)

In [22]:
#Calculating score on Train data
rf.score(X_train, y_train)

0.9564606741573034

In [23]:
#Calculating score on Test data
rf.score(X_test, y_test)

0.8212290502793296

In [24]:
#Viewing Feature Importance
rf.feature_importances_

array([0.21142339, 0.2410532 , 0.04118783, 0.02139693, 0.05024351,
       0.16041295, 0.11566534, 0.01570911, 0.02253486, 0.00563129,
       0.00741374, 0.00373597, 0.00048017, 0.00278653, 0.02060513,
       0.01525366, 0.01216005, 0.00139989, 0.00259109, 0.00193676,
       0.00039316, 0.02291567, 0.00751666, 0.01555309])

In [25]:
#Feature Importance of each variable
pd.Series(rf.feature_importances_, index=X_train.columns)

Age           0.211423
Fare          0.241053
Pclass_1      0.041188
Pclass_2      0.021397
Pclass_3      0.050244
Sex_female    0.160413
Sex_male      0.115665
SibSp_0       0.015709
SibSp_1       0.022535
SibSp_2       0.005631
SibSp_3       0.007414
SibSp_4       0.003736
SibSp_5       0.000480
SibSp_8       0.002787
Parch_0       0.020605
Parch_1       0.015254
Parch_2       0.012160
Parch_3       0.001400
Parch_4       0.002591
Parch_5       0.001937
Parch_6       0.000393
Embarked_C    0.022916
Embarked_Q    0.007517
Embarked_S    0.015553
dtype: float64